#!/bin/sh

function mkpatch() {
	PATCH=$1
	cat > $PATCH << EOF
This patch adds the descriptor for the 7-segment LED display of X92.

EOF
	diff -u g12a_s905x2_u211.dts $2 >> $PATCH
}

mkpatch ../../../build/X96max/x96max-dts-4g.patch g12a_x96max_4g.dts
mkpatch ../../../build/X96max/x96max-dts-3g.patch g12a_x96max_3g.dts
mkpatch ../../../build/X96max/x96max-dts-2g.patch g12a_x96max_2g.dts
