#!/bin/sh

PATCH=../../build/X92/kernel/linux-3.14-x92-gpu-clk.patch

cat > $PATCH << EOF
This patch removes the unneeded gpu_clk driver as it fails
to initialize anyway. It looks like the functionality of this
driver is built into the mali driver itself.

EOF

diff -ur original modified >> $PATCH
