#!/bin/sh

PATCH=../../build/patches/bcmdhd_1_201_59_x/001-staticbuf.patch

cat > $PATCH << EOF
Change CONFIG_DHD_USE_STATIC_BUF to CONFIG_BCMDHD_USE_STATIC_BUF everywhere through
the Broadcom AP6xxx driver as it has been changed in kernel.

EOF

diff -ur original modified >> $PATCH
