#!/bin/sh

PATCH=../../../build/X92/x92-dts.patch

cat > $PATCH << EOF
This patch adds the descriptor for the 7-segment LED display of X92.
Also it adds a section for the old remote control driver from
Beijing-platform. There is already a remote control section in
mesongxm.dti (which is included from gxm_q201*.dts), but that one
is for the new driver (which must be disabled in kernel config).

Also it modifies the Ethernet section to specify a gigabit
controller rather than the 100MBit used in q201 dts, and disables
the USB3 hub since there are no USB3 connectors in X92.

EOF

diff -u gxm_q201_2g.dts gxm_x92_2g.dts >> $PATCH
