#!/bin/sh

PATCH=../../build/patches/linux-3.14/linux-3.14-x92-remote.patch

cat > $PATCH << EOF
This patch enables the old remote control driver by Beijing-platform
instead of the new one by AMLOGIC. The new driver does not work well
on X92, also it does not support mouse mode.

EOF

diff -ur original modified >> $PATCH
