#!/bin/sh

PATCH=../../build/X92/kernel/linux-3.14-x92-rfkill.patch

cat > $PATCH << EOF
This patch relaxes security checks for writing the /sys/class/rfkill/*/state
attribute. Normally it would check for CAP_NET_ADMIN but X92 firmware supposes
it's limited only by filesystem access rights.

EOF

diff -ur original modified >> $PATCH
